//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.01 at 03:12:44 PM CET 
//


package com.example.demo.demo.discounts;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.demo.demo.discounts package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.demo.demo.discounts
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DiscountResponse }
     * 
     */
    public DiscountResponse createDiscountResponse() {
        return new DiscountResponse();
    }

    /**
     * Create an instance of {@link Discount }
     * 
     */
    public Discount createDiscount() {
        return new Discount();
    }

    /**
     * Create an instance of {@link DiscountByStatusAndTypeRequest }
     * 
     */
    public DiscountByStatusAndTypeRequest createDiscountByStatusAndTypeRequest() {
        return new DiscountByStatusAndTypeRequest();
    }

    /**
     * Create an instance of {@link DiscountAbove45Request }
     * 
     */
    public DiscountAbove45Request createDiscountAbove45Request() {
        return new DiscountAbove45Request();
    }

    /**
     * Create an instance of {@link DiscountEndingIn2DaysRequest }
     * 
     */
    public DiscountEndingIn2DaysRequest createDiscountEndingIn2DaysRequest() {
        return new DiscountEndingIn2DaysRequest();
    }

}
