//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.01 at 03:12:44 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://demo.demo.example.com/discounts", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.demo.demo.discounts;
